name: build and release

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up requirements for Linux
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo sed -i -e 's/^deb /deb [arch=amd64,arm64] /' /etc/apt/sources.list
        sudo dpkg --add-architecture arm64
        sudo apt update -qq -y
        sudo apt install -qq -y gcc gcc-aarch64-linux-gnu xorg-dev
        sudo apt install -qq -y libc6-dev       libx11-dev       libxtst-dev
        sudo apt install -qq -y libc6-dev:arm64 libx11-dev:arm64 libxtst-dev:arm64
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Build
      run: |
        make tidy
        make all
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: bin/kmactor-*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: artifact
        path: ./
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: kmactor-*
