name: build and release

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up requirements for Linux
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt update -y
        sudo apt install gcc libc6-dev -y
        sudo apt install libx11-dev xorg-dev libxtst-dev -y
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Build
      run: |
        make tidy
        make all
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: bin/kmactor-*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: artifact
        path: ./
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: kmactor-*
