name: build and release

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up requirements for Linux
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt update -y
        sudo apt install gcc libc6-dev -y
        sudo apt install libx11-dev xorg-dev libxtst-dev -y
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: Build
      run: |
        make release
    - name: Rename for Windows
      if: ${{ matrix.os == 'windows-latest' }}
      run: mv bin/kmactor bin/kmactor-windows-latest.exe
    - name: Rename for macOS
      if: ${{ matrix.os == 'macos-latest' }}
      run: mv bin/kmactor bin/kmactor-macos-latest
    - name: Rename for Linux
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: mv bin/kmactor bin/kmactor-linux-latest
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: artifact
        path: bin/kmactor-*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: artifact
        path: ./
    - name: Download SSL certificate
      run: |
        wget -O localhost.direct.zip https://aka.re/localhost
        unzip -P localhost localhost.direct.zip
        mv localhost.direct.crt cert.pem
        mv localhost.direct.key key.pem
        rm localhost.direct.zip
    - name: Zip package
      run: |
        zip kmactor-windows.zip *.pem kmactor-windows-latest.exe
        zip kmactor-macos.zip *.pem kmactor-macos-latest
        zip kmactor-linux.zip *.pem kmactor-linux-latest
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        files: |
          cert.pem, key.pem
          kmactor-windows.zip, kmactor-windows-latest.exe
          kmactor-macos.zip kmactor-macos-latest
          kmactor-linux.zip kmactor-linux-latest
