name: build

on: workflow_dispatch

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Set up requirements on ubuntu-latest
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        sudo apt update -y
        sudo apt install gcc libc6-dev -y
        sudo apt install libx11-dev xorg-dev libxtst-dev -y
        sudo apt install libpng++-dev -y
        sudo apt install xcb libxcb-xkb-dev x11-xkb-utils libx11-xcb-dev libxkbcommon-x11-dev libxkbcommon-dev -y
        sudo apt install xsel xclip -y
    - name: Set up requirements on windows-latest
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        set PATH
        dir C:\mingw64\bin
    - name: Set up requirements on macos-latest
      if: ${{ matrix.os == 'macos-latest' }}
      run: echo macos-latest
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    - name: tidy
      run: make tidy
    - name: build for ${{ matrix.os }}
      run: make release
